ejb.provider-url=remote+http://localhost:8080

ejb.beneficio.jndi=ejb:/ejb-module/BeneficioEjbService!com.example.ejb.BeneficioEjbRemote

server.port=8082
spring.datasource.url=jdbc:h2:file:C:/projeto-sicobb/db_beneficio;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/seed.sql
spring.sql.init.schema-locations=classpath:db/schema.sql