
DELETE FROM BENEFICIO;

INSERT INTO BENEFICIO (ID, NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES
(1, 'Beneficio A', 'Descrição A', 1000.00, TRUE, 0),
(2, 'Beneficio B', 'Descrição B', 500.00, TRUE, 0);

ALTER TABLE BENEFICIO ALTER COLUMN ID RESTART WITH 3;